name: smo_workspace

sdkPath: .fvm/flutter_sdk

packages:
  - app/**
  - core/**
  - feature/**

ide:
  intellij: false

command:
  bootstrap:
    hooks:
      post: |
        melos build_runner
        dart run husky install
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  check:all:
    run: |
      melos analyze --no-select
      melos format:check --no-select
    description: check follow analyze & format in all code.

  fix:all:
    run: |
      melos fix --no-select
      melos format --no-select
    description: Fix follow analyze & format in all code.

  analyze:
    run: melos exec -c 6 -- "flutter analyze"
    description: Run `flutter analyze` in all packages
    # packageFilters:
    #   ignore: []

  fix:
    run: melos exec -c 6 -- "dart fix . --apply"
    description: Format Dart code.

  format:
    run: melos exec -c 6 -- "dart format ."
    description: Format Dart code.

  format:check:
    run: melos exec -c 6 -- "dart format . --set-exit-if-changed"
    description: Run check format in all packages

  test:
    # Only run the test command when the package has a test directory
    run: melos exec -c 6 --fail-fast --dir-exists=test -- "flutter test --no-pub --coverage"
    description: Run `flutter test --no-pub --coverage` in all packages

  build:all:
    run: |
      melos build_runner --no-select

  build_runner:
    run: melos exec -c 6 -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run `flutter pub run build_runner build --delete-conflicting-outputs` in all packages
